services:
  palworld:
    image: jammsen/palworld-dedicated-server:latest
    restart: always
    network_mode: bridge
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
    environment:
      - TIMEZONE=Asia/Shanghai
      - ALWAYS_UPDATE_ON_START=true
      - MAX_PLAYERS=32
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - RCON_ENABLED=true
      - PUBLIC_PORT=8211
      - SERVER_NAME=Palworld Private Server-###RANDOM###
      - SERVER_DESCRIPTION=Palworld Private Server
      - SERVER_PASSWORD=server123
      - ADMIN_PASSWORD=admin123
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
    volumes:
      - ./game:/palworld
    deploy:
      resources:
        limits:
          memory: 10G

  rcon:
    image: outdead/rcon:latest
    entrypoint: ['/rcon', '-a', 'palworld:25575', '-p', 'admin123']
    profiles: ['rcon']